name: Run Python Script

on:
  workflow_dispatch:
    # Input to provide the path to the Python script
    inputs:
      path:
        description: 'Path to the Python script to run'
        required: true
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run Python script
      run: python ${{ inputs.path }}
