name: Run Python script

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas numpy matplotlib ipython yfinance
        
    - name: Run script
      run: python ${{ github.workspace }}/Market_Analysis_App/main.py

    - name: Configure Git
      uses: angelosuinan/github-config-action@v1
      with:
        user.name: gilbertycc
        user.email: test@text.com

    - name: Add and commit changes
      uses: EndBug/add-and-commit@v7.0.0
      with:
        message: 'Update index.html'
        add: 'index.html'
    
    
    - name: Push changes
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.S1 }}
        script: |
          const { context, GitHub } = require('@actions/github');
          const { owner, repo } = context.repo;
          const gitHub = new GitHub(process.env.GITHUB_TOKEN);
          gitHub.repos.createOrUpdateFileContents({
            owner,
            repo,
            path: '${{ github.workspace }}/docs/index.html',
            message: 'Add index.html',
            content: Buffer.from('index.html').toString('base64'),
            sha: context.payload.before,
            branch: context.payload.ref.replace('refs/heads/', ''),
          });

