name: Run Python script

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas numpy matplotlib ipython yfinance
        
    - name: Display root directory
      run: |
        cd "${{ github.workspace }}"
        pwd
        ls

    #- name: Run script
    #  run: python ${{ github.workspace }}/Market_Analysis_App/main.py
      
    - name: Display report directory
      run: |
        cd "${{ github.workspace }}/docs"
        pwd
        ls
      
    - name: Upload report
        uses: actions/upload-artifact@v3
        with:
            name: report
            path: index.html

    - name: Upload report2
        uses: actions/upload-artifact@v3
        with:
            name: report
            path: ${{ github.workspace }}/docs/index.html
