name: Run Python script
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_script:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      #- name: Install dependencies
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install yfinance pandas numpy matplotlib ipython yfinance

      #- name: Run script
      #  run: python ${{ github.workspace }}/Market_Analysis_App/main.py
      - name: Move file
        run: |
          mv ${{ github.workspace }}/docs/index.html ${{ github.workspace }}/docs/index.html.bak
      - name: GIT commit and push docs
        env: 
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "gilbertycc/myCodes"
          git config --global user.email "gilbertycc@users.noreply.github.com"
          git add docs
          git commit -m "Testing workflow"
          git push


