name: Generate Stock Report and Deploy
on:
  # trigger the report generation from Mon to Fri at 2000
  schedule:
    - cron: "00 23 * * 1-5"
  workflow_dispatch:

jobs:
  Trigger_Report_Generation_Workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Python Runtime env
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies on Runtime env
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy matplotlib ipython==7.16.1 yfinance torch torchsummary

      - name: Run Python script
        run: python ${{ github.workspace }}/Market_Analysis_App/main.py
        
      - name: Move the report to the docs dir
        run: |
          mv -f ${{ github.workspace }}/index.html ${{ github.workspace }}/docs/index.html

      - name: Commit the new report
        run: |
          git config --local user.email "windycc@users.noreply.github.com"
          git config --local user.name "windycc"
          git commit -a -m "Deploy Stock Report to Github Page"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
